### ISSUE TITLE
Compilation error after PR #93

### ISSUE THREAD

**Issue by DrUm78** [rtissera/libchdr#98]
Hello,

PR #93 introduced a compilation error:
```
pico/cd/libchdr/src/libchdr_flac.c:16:10: fatal error: dr_flac.h: No such file or directory
   16 | #include <dr_flac.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:405: pico/cd/libchdr/src/libchdr_flac.o] Error 1
```
Indeed, `dr_flac.h` is in `deps/dr_libs/` but the include in `src/libchdr_flac.c` is:
```
#include <dr_flac.h>
```
Of course I can fix the include path myself, but just wanted to let you know.

**Comment by rtissera** [comment]
Thanks I merged a bunch of commits and fixes from @scribam recently probably linked to.

**Comment by scribam** [comment]
@DrUm78 do you use a custom Makefile or do you have the error with cmake? how can I reproduce your compilation error?

**Comment by DrUm78** [comment]
@scribam I use PicoDrive Makefile here: https://github.com/irixxxx/picodrive/blob/3a77090514c3ba3c1a0286a046bc9fe323e07f27/Makefile#L319
You can reproduce it by compiling this repo under x86_64 for instance after a `git submodule update --init`.

Same issue when compiling libchdr within PCSX: https://github.com/notaz/pcsx_rearmed too.

**Comment by scribam** [comment]
I made a pull request to revert the offending commit and keep the compatibility with current Makefiles

**Comment by rtissera** [comment]
Revert merged please confirm issue is fixed.

**Comment by DrUm78** [comment]
All good now, thanks guys. 👍
